document.write( '<div id= \"footer\">' );
document.write( '	<div id=\"footer-adjust\">' );
document.write( '		<div id=\"modFooter\">' );
document.write( '			<div id=\"modCreditsHeader\">Credits</div>');
document.write( '			<div id=\"modCreditedPrograms\">');
document.write( '				<div class=\"CreditedMod\">');
document.write( '					<a href=\"http://aok.heavengames.com/blacksmith/showfile.php?fileid=11002\" target=\"_blank\">Advanced Genie Editor</a>' );
document.write( '					<br /><span class=\"footerExplanation\">Used for editing .DAT files</span>');
document.write( '				</div>' );
document.write( '				<div class=\"CreditedMod\">');
document.write( '					<a href=\"http://aok.heavengames.com/blacksmith/showfile.php?fileid=11349\" target=\"_blank\">Turtle Pack</a>' );
document.write( '					<br><span class=\"footerExplanation\">Used for editing .DRS and .SLP files</span>');
document.write( '				</div>' );
document.write( '				<div class=\"CreditedMod\">');
document.write( '					<a href=\"https://github.com/MeryKitty/meryslp\" target=\"_blank\">Mery SLP</a>');
document.write( '					<br><span class=\"footerExplanation\">Used for editing .SLP files in AOE:DE</span>');
document.write( '				</div>' );
document.write( '				<div class=\"CreditedMod\">');
document.write( '					<a href=\"http://aok.heavengames.com/blacksmith/showfile.php?fileid=13179" target=\"_blank\">SLX Studio</a>');
document.write( '					<br><span class=\"footerExplanation\">Used for editing .SLP files in AOE:RoR</span>');
document.write( '				</div>' );
document.write( '				<div class=\"CreditedMod\">');
document.write( '					<a href=\"http://aoe.heavengames.com/dl-php/showfile.php?fileid=2585\" target=\"_blank\">Heavy Slinger</a>');
document.write( '					<br><span class=\"footerExplanation\">Used for Bronze Age Slinger graphics.</span>');
document.write( '				</div>' );
document.write( '				<div class=\"CreditedMod\">');
document.write( '					<a href=\"https://aoe.heavengames.com/dl-php/showfile.php?fileid=2590\" target=\"_blank\">Heavy Camel Rider</a>');
document.write( '					<br><span class=\"footerExplanation\">Used for Iron Age Camel Rider graphics.</span>');
document.write( '				</div>' );
document.write( '			</div>');
document.write( '		</div>');
document.write( '	    <div id=\"siteWaterMarks\">© 2021 Microsoft. All rights reserved. <br> © 2018-2021 RM Brawl. All rights reserved.</div>');
document.write( '	</div>');
document.write( '</div>');