document.write("<div id=\"topSticky\">");
document.write("	<div class=\"top-list-left\">");
document.write("	<\/div>");
document.write("	<div class=\"top-list\">");
document.write("		<div class=\"brawl\">");
document.write("			<a href=\"index.html\"><img src=\"Pictures\/others\/name.png\" width=\"151\" height=\"45\" alt=\"RM Brawl\" \/><\/a>");
document.write("		 <\/div>");
document.write("		<div class=\"navbar\">");
document.write("			<a href=\"index.html\" class=\"top-link\">Home<\/a>");
document.write("			<div class=\"dropdown\">");
document.write("				<a href=\"aoe-de.html\" class=\"top-link\">Patch notes<\/a> ");
document.write("					<div class=\"dropdown-content\">");
document.write("						<a href=\"1,27-patch.html\" class=\"drop-link\">Patch 1.27 notes<\/a>");
document.write("						<a href=\"olderPatchNotes.html\" class=\"drop-link\">Older patch notes<\/a>");
document.write("						<a href=\"upatch.html\" class=\"drop-link\">Change log UPatch<\/a>");
document.write("						<a href=\"1,0a.html\" class=\"drop-link\">Change log 1.0a<\/a>");
document.write("						<a href=\"aoe-de.html\" class=\"drop-link\">Change log DE<\/a>");
document.write("					<\/div>");
document.write("			<\/div> ");
document.write("			<a href=\"info.html\" class=\"top-link\">Unit information<\/a>");
document.write("			<a href=\"civs.html\" class=\"top-link\">Tech trees<\/a>");
document.write("			<div class=\"dropdown\">");
document.write("				<a href=\"more.html\" class=\"top-link\">More<\/a> ");
document.write("					<div class=\"dropdown-content\">");
document.write("						<a href=\"playerColorEditor.html\" class=\"drop-link\">Player Color Editor<\/a>");
document.write("						<a href=\"treeDrawLevel.html\" class=\"drop-link\">Tree Draw Level<\/a>");
document.write("						<a href=\"upcomingChanges.html\" class=\"drop-link\">Future Changes<\/a>");
document.write("						<a href=\"credits.html\" class=\"drop-link\">Credits<\/a>");
document.write("					<\/div>");
document.write("			<\/div> ");
document.write("		<\/div>");
document.write("	<\/div>");
document.write("<\/div>");
document.write("<div class=\"backgroundlist\"> <\/div>");